name: Setup and start Minikube
description: A GitHub Action to install and start Minikube with the Docker driver

runs:
  using: 'composite'
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Install Minikube
      shell: bash
      run: |
        curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

    - name: Start Minikube (Docker driver)
      shell: bash
      run: |
        minikube start --driver=docker --wait=all
        kubectl get nodes